import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const horizontalPadding = 24;
const imageSize = screenWidth - horizontalPadding * 2;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  inner: {
    paddingHorizontal: 24,
    paddingTop: 0,
    paddingBottom: 0,
    width: '100%',
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 14,
  },
  backArrow: {
    fontSize: 14,
    color: '#A9A9A9',
    marginRight: 4,
    marginTop: Platform.OS === 'ios' ? 0 : -2,
    fontFamily: 'Inter18Bold',
  },
  backText: {
    color: '#A9A9A9',
    fontSize: 13,
    fontFamily: 'Inter18Regular',
  },
  imageWrap: {
    width: imageSize,
    height: imageSize * 0.8,
    borderRadius: 8,
    overflow: 'hidden',
    alignSelf: 'center',
    backgroundColor: '#fafafa',
    marginBottom: 10,
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: 8,
  },
  title: {
    fontFamily: 'Inter18Bold',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 19,
    color: '#1A1A1A',
    marginTop: 8,
    marginBottom: 7,
  },
  description: {
    fontFamily: 'Inter18Regular',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 15,
    color: '#A9A9A9',
    marginBottom: 12,
  },
  sectionTitle: {
    fontFamily: 'Inter18Bold',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 17,
    color: '#1A1A1A',
    marginBottom: 7,
  },
  sizeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 4,
    gap: 8,
  },
  sizeBtn: {
    paddingVertical: 7,
    paddingHorizontal: 18,
    borderRadius: 7,
    backgroundColor: '#FAFAFA',
    borderWidth: 1,
    borderColor: 'transparent',
    marginBottom: 8,
    minWidth: 74,
    maxWidth: 110,
  },
  sizeBtnActive: {
    backgroundColor: '#FFF2DF',
    borderColor: '#FF9900',
  },
  sizeBtnText: {
    fontFamily: 'Inter18Medium',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 14,
    color: '#A1A1A1',
  },
  sizeBtnTextActive: {
    color: '#FF9900',
  },
  price: {
    fontFamily: 'Inter18Bold',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 24,
    color: '#FF9900',
    marginTop: 4,
    marginBottom: 4,
  },
  rub: {
    fontFamily: 'Inter18Bold',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 24,
    color: '#FF9900',
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 10,
    marginTop: 8,
  },
  addBtn: {
    flexGrow: 1,
    flexShrink: 1,
    backgroundColor: '#FF9900',
    borderRadius: 5,
    paddingVertical: 8,
    paddingHorizontal: 16,
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: 32,
    flexDirection: 'row',
    gap: 8,
    minWidth: 80,
    maxWidth: 180,
  },
  addBtnText: {
    color: '#fff',
    fontFamily: 'Inter18Bold',
    fontWeight: '700',
    fontSize: 16,
    lineHeight: 19,
  },
  qtyBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D2D2D2',
    height: 36,
    backgroundColor: '#fff',
    justifyContent: 'center',
    paddingHorizontal: 0, // убираем общий паддинг, будет у иконок!
  },
  qtyBtn: {
    width: 28,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 7, // <-- вот тут паддинг!
  },
  qtyBtnText: {
    fontSize: 20,
    fontFamily: 'Inter18Bold',
    color: '#1A1A1A',
    lineHeight: 24,
    textAlign: 'center',
  },
  qtyBtnDisabled: { color: '#D2D2D2' },
  qtyText: {
    fontFamily: 'Inter18Regular',
    fontSize: 16,
    color: '#1A1A1A',
    includeFontPadding: false,
    minWidth: 70, // фикс для веса, можно 28 для штук
    maxWidth: 60,
    textAlign: 'center',
    marginHorizontal: -5,
    paddingHorizontal: 2, // у текста нет доп. отступа!
  },
  qtyUnitLabel: {
    color: '#A9A9A9',
    fontSize: 14,
    fontFamily: 'Inter18Regular',
  },
});
