// productsImagesMap.ts
export const productImages: Record<string, any> = {
  'xxl_shawarma.png': require('../assets/img/products/defolt.png'),
  'pizza_margherita.png': require('../assets/img/products/pizza/pizza_margherita.png'),

  //cheburek_yantyk
  'yantyk.png': require('../assets/img/products/cheburek_yantyk/yantyk.png'),
  'cheburek.png': require('../assets/img/products/cheburek_yantyk/cheburek.png'),

  //salads
  //'olivier.png': require('../assets/img/products/salad/olivier.png'),
  'crab_pineapple_salad.png': require('../assets/img/products/salad/crab_pineapple_salad.png'),
  'eggplant_salad.png': require('../assets/img/products/salad/eggplant_salad.png'),
  //'sea_cocktail_salad.png': require('../assets/img/products/salad/sea_cocktail_salad.png'),
  'caesar_salad.png': require('../assets/img/products/salad/caesar_salad.png'),
  'beef_pomegranate_salad.png': require('../assets/img/products/salad/beef_pomegranate_salad.png'),
  'greek_salad.png': require('../assets/img/products/salad/greek_salad.png'),
  //'layered_salmon_rice_salad.png': require('../assets/img/products/salad/layered_salmon_rice_salad.png'),
  //'shakarop.png': require('../assets/img/products/salad/shakarop.png'),
  'mushroom_chicken_salad.png': require('../assets/img/products/salad/mushroom_chicken_salad.png'),

  //hot_dishes
  'plov.png': require('../assets/img/products/hot_dishes/plov.png'),
  'manti.png': require('../assets/img/products/hot_dishes/manti.png'),
  'kazan_kebab.png': require('../assets/img/products/hot_dishes/kazan_kebab.png'),
  'nokhut_lamb.png': require('../assets/img/products/hot_dishes/nokhut_lamb.png'),
  'pelmeshki.png': require('../assets/img/products/hot_dishes/pelmeshki.png'),
  'sarma.png': require('../assets/img/products/hot_dishes/sarma.png'),
  //'polo_de_bianca.png': require('../assets/img/products/hot_dishes/polo_de_bianca.png'),

  //soups
  'shurpa.png': require('../assets/img/products/soups/shurpa.png'),
  'lagman.png': require('../assets/img/products/soups/lagman.png'),
  'merdzhimek.png': require('../assets/img/products/soups/merdzhimek.png'),
  'yufak_ash.png': require('../assets/img/products/soups/yufak_ash.png'),
  'kuksi.png': require('../assets/img/products/soups/kuksi.png'),
  //'tom_yam.png': require('../assets/img/products/soups/tom_yam.png'),
  //'mushroom_soup.png': require('../assets/img/products/soups/mushroom_soup.png'),

  //desserts
  'maffin.png': require('../assets/img/products/desserts/maffin.png'),
  'cheesecake_new_york.png': require('../assets/img/products/desserts/cheesecake_new_york.png'),
  'meringue_roll.png': require('../assets/img/products/desserts/meringue_roll.png'),
  'syrniki.png': require('../assets/img/products/desserts/syrniki.png'),
  'rafaello_cake.png': require('../assets/img/products/desserts/rafaello_cake.png'),
  'dubai_cake.png': require('../assets/img/products/desserts/dubai_cake.png'),
  'milk_girl.png': require('../assets/img/products/desserts/milk_girl.png'),
  'three_chocolate_cake.png': require('../assets/img/products/desserts/three_chocolate_cake.png'),
  'snickers_cake.png': require('../assets/img/products/desserts/snickers_cake.png'),
  'medovik.png': require('../assets/img/products/desserts/medovik.png'),
  'red_velvet.png': require('../assets/img/products/desserts/red_velvet.png'),
  'trifle_snickers.png': require('../assets/img/products/desserts/trifle_snickers.png'),
  'donuts.png': require('../assets/img/products/desserts/donuts.png'),
  'trifle_tiramisu.png': require('../assets/img/products/desserts/trifle_tiramisu.png'),
  'berry_mary.png': require('../assets/img/products/desserts/berry_mary.png'),
  //'macarons.png': require('../assets/img/products/desserts/macarons.png'),
  //'cheesecake.png': require('../assets/img/products/desserts/cheesecake.png'),
  //'dubai_cheesecake.png': require('../assets/img/products/desserts/dubai_cheesecake.png'),
  //'mousse_dessert.png': require('../assets/img/products/desserts/mousse_dessert.png'),
  //'truffle.png': require('../assets/img/products/desserts/truffle.png'),
  //'tiramisu.png': require('../assets/img/products/desserts/tiramisu.png'),
  //'pancakes.png': require('../assets/img/products/desserts/pancakes.png'),
  //'eclairs.png': require('../assets/img/products/desserts/eclairs.png'),
  //'san_sebastian.png': require('../assets/img/products/desserts/san_sebastian.png'),
  //'croissant.png': require('../assets/img/products/desserts/croissant.png'),
  //'blin_napoleon.png': require('../assets/img/products/desserts/blin_napoleon.png'),
  //'rafaello_cake.png': require('../assets/img/products/desserts/rafaello_cake.png'),
  //'san_sebastian.png': require('../assets/img/products/desserts/san_sebastian.png'),

  //pizza
  //'pizza_margarita.png': require('../assets/img/products/pizza/pizza_margarita.png'),
  //'pizza_kuritsa_mangal.png': require('../assets/img/products/pizza/pizza_kuritsa_mangal.png'),
  //'pizza_zhulen.png': require('../assets/img/products/pizza/pizza_zhulen.png'),
  //'pizza_govyadina_mangal.png': require('../assets/img/products/pizza/pizza_govyadina_mangal.png'),
  //'pizza_gavayskaya.png': require('../assets/img/products/pizza/pizza_gavayskaya.png'),
  //'pizza_tsezar.png': require('../assets/img/products/pizza/pizza_tsezar.png'),
  //'pizza_kopchennaya_kuritsa.png': require('../assets/img/products/pizza/pizza_kopchennaya_kuritsa.png'),
  //'pizza_ohotnichya.png': require('../assets/img/products/pizza/pizza_ohotnichya.png'),
  //'pizza_pepperoni.png': require('../assets/img/products/pizza/pizza_pepperoni.png'),
  //'pizza_kopchennoe_myaso.png': require('../assets/img/products/pizza/pizza_kopchennoe_myaso.png'),
  //'pizza_vetchina.png': require('../assets/img/products/pizza/pizza_vetchina.png'),
  //'pizza_4_syra.png': require('../assets/img/products/pizza/pizza_4_syra.png'),
  //'pizza_4_myasa.png': require('../assets/img/products/pizza/pizza_4_myasa.png'),
  //'pizza_assorti.png': require('../assets/img/products/pizza/pizza_assorti.png'),
  //'pizza_morskaya.png': require('../assets/img/products/pizza/pizza_morskaya.png'),

  //rolls
  //'filadelfiya_v_syre.png': require('../assets/img/products/rolls/filadelfiya_v_syre.png'),
  //'filadelfiya_v_tuntse.png': require('../assets/img/products/rolls/filadelfiya_v_tuntse.png'),
  //'filadelfiya_v_krevetke.png': require('../assets/img/products/rolls/filadelfiya_v_krevetke.png'),
  //'filadelfiya_v_kopchennom_losose.png': require('../assets/img/products/rolls/filadelfiya_v_kopchennom_losose.png'),
  //'filadelfiya_v_ugre.png': require('../assets/img/products/rolls/filadelfiya_v_ugre.png'),
  //'filadelfiya_klassika.png': require('../assets/img/products/rolls/filadelfiya_klassika.png'),
  //'set_filamaniya_miks.png': require('../assets/img/products/rolls/set_filamaniya_miks.png'),
  //'set_vostok_gold.png': require('../assets/img/products/rolls/set_vostok_gold.png'),
  //'roll_ostryy_losos.png': require('../assets/img/products/rolls/roll_ostryy_losos.png'),
  //'roll_mayami.png': require('../assets/img/products/rolls/roll_mayami.png'),
  //'roll_fukusima.png': require('../assets/img/products/rolls/roll_fukusima.png'),
  //'roll_tayfun.png': require('../assets/img/products/rolls/roll_tayfun.png'),
  //'roll_bansay.png': require('../assets/img/products/rolls/roll_bansay.png'),
  //'roll_filadelfiya_v_ugre.png': require('../assets/img/products/rolls/roll_filadelfiya_v_ugre.png'),
  //'roll_alyaska.png': require('../assets/img/products/rolls/roll_alyaska.png'),
  //'roll_chiken.png': require('../assets/img/products/rolls/roll_chiken.png'),
  //'roll_sakura.png': require('../assets/img/products/rolls/roll_sakura.png'),
  //'roll_ringo.png': require('../assets/img/products/rolls/roll_ringo.png'),
  //'roll_nevada.png': require('../assets/img/products/rolls/roll_nevada.png'),
  //'roll_osaka.png': require('../assets/img/products/rolls/roll_osaka.png'),
  //'roll_cpaysi_losos.png': require('../assets/img/products/rolls/roll_cpaysi_losos.png'),
  //'roll_drakon.png': require('../assets/img/products/rolls/roll_drakon.png'),
  //'roll_unagi.png': require('../assets/img/products/rolls/roll_unagi.png'),
  //'roll_leys.png': require('../assets/img/products/rolls/roll_leys.png'),
  //'roll_morskoy.png': require('../assets/img/products/rolls/roll_morskoy.png'),
  //'roll_fyuzhn.png': require('../assets/img/products/rolls/roll_fyuzhn.png'),
  //'roll_kaliforniya_v_masago.png': require('../assets/img/products/rolls/roll_kaliforniya_v_masago.png'),
  //'roll_akito.png': require('../assets/img/products/rolls/roll_akito.png'),
  //'roll_abiko.png': require('../assets/img/products/rolls/roll_abiko.png'),
  //'roll_kaliforniya_v_kunzhute.png': require('../assets/img/products/rolls/roll_kaliforniya_v_kunzhute.png'),
  //'roll_zelenyy_drakon.png': require('../assets/img/products/rolls/roll_zelenyy_drakon.png'),
  //'roll_legenda.png': require('../assets/img/products/rolls/roll_legenda.png'),
  //'roll_chiken_chiz.png': require('../assets/img/products/rolls/roll_chiken_chiz.png'),
  //'roll_mikado.png': require('../assets/img/products/rolls/roll_mikado.png'),
  //'roll_kurodo.png': require('../assets/img/products/rolls/roll_kurodo.png'),
  //'roll_nezhnyy.png': require('../assets/img/products/rolls/roll_nezhnyy.png'),
  //'roll_fudzhi.png': require('../assets/img/products/rolls/roll_fudzhi.png'),
  //'roll_filadelfiya_gril.png': require('../assets/img/products/rolls/roll_filadelfiya_gril.png'),
  //'maki_s_lososem.png': require('../assets/img/products/rolls/maki_s_lososem.png'),
  //'maki_s_krabom.png': require('../assets/img/products/rolls/maki_s_krabom.png'),
  //'maki_s_krevetkoy.png': require('../assets/img/products/rolls/maki_s_krevetkoy.png'),
  //'maki_s_ogurtsom.png': require('../assets/img/products/rolls/maki_s_ogurtsom.png'),
  //'maki_s_ugrem.png': require('../assets/img/products/rolls/maki_s_ugrem.png'),
  //'losos.png': require('../assets/img/products/rolls/losos.png'),
  //'losos_zapechennyy.png': require('../assets/img/products/rolls/losos_zapechennyy.png'),
  //'sushi_2sht_ugor_zapechennyy.png': require('../assets/img/products/rolls/sushi_2sht_ugor_zapechennyy.png'),
  //'sushi_2sht_tigrovaya_krevetka_yaki.png': require('../assets/img/products/rolls/sushi_2sht_tigrovaya_krevetka_yaki.png'),
  //'sushi_2sht_krevetka_ostraya.png': require('../assets/img/products/rolls/sushi_2sht_krevetka_ostraya.png'),
  //'sushi_2sht_ugor_.png': require('../assets/img/products/rolls/sushi_2sht_ugor_.png'),
  //'sushi_2sht_ugor_ostryy.png': require('../assets/img/products/rolls/sushi_2sht_ugor_ostryy.png'),
  //'klassika_510g.png': require('../assets/img/products/rolls/klassika_510g.png'),
  //'miks_710g.png': require('../assets/img/products/rolls/miks_710g.png'),
  //'udur-budur_730g.png': require('../assets/img/products/rolls/udur-budur_730g.png'),
  //'tempura_710g.png': require('../assets/img/products/rolls/tempura_710g.png'),
  //'salamandra_600g.png': require('../assets/img/products/rolls/salamandra_600g.png'),
  //'obed_samuraya.png': require('../assets/img/products/rolls/obed_samuraya.png'),
  //'han_set.png': require('../assets/img/products/rolls/han_set.png'),

  //fresh
  'fresh_hod_nogi.png': require('../assets/img/products/fresh/fresh_hod_nogi.png'),
  //'fresh_tashdemir.png': require('../assets/img/products/fresh/fresh_tashdemir.png'),
  'fresh_ne_hodi_golodnyy.png': require('../assets/img/products/fresh/fresh_ne_hodi_golodnyy.png'),
  //'fresh_mushinskiy.png': require('../assets/img/products/fresh/fresh_mushinskiy.png'),
  'fresh_apelsinovyy.png': require('../assets/img/products/fresh/fresh_apelsinovyy.png'),
  'fresh_granatovyy.png': require('../assets/img/products/fresh/fresh_granatovyy.png'),
  'fresh_morkovnyy.png': require('../assets/img/products/fresh/fresh_morkovnyy.png'),
  //'fresh_arbuz.png': require('../assets/img/products/fresh/fresh_arbuz.png'),
  //'fresh_dynya.png': require('../assets/img/products/fresh/fresh_dynya.png'),
  //'fresh_granat_apelsin.png': require('../assets/img/products/fresh/fresh_granat_apelsin.png'),
  'fresh_greypfrut_apelsin.png': require('../assets/img/products/fresh/fresh_greypfrut_apelsin.png'),
  'fresh_greypfrut_granat.png': require('../assets/img/products/fresh/fresh_greypfrut_granat.png'),
};
