import { StyleSheet } from 'react-native';

export const savedAddressListStyles = StyleSheet.create({
  listContent: {
    borderRadius: 10,
    paddingVertical: 20,
    paddingHorizontal: 24,
    marginBottom: 10,
  },
  addressItem: {
    backgroundColor: '#FFF2DC',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 17,
    marginBottom: 10,
    minHeight: 71,
    width: '100%',
  },
  swipeDeleteWrapper: {
    borderRadius: 10,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'flex-end',
    height: 71,
    width: 90,
    backgroundColor: 'transparent',
  },
  deleteButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    height: 71,
    width: 90,
  },
  deleteText: {
    color: '#fff',
    fontSize: 16,
    fontFamily: 'Inter18Bold',
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#FF9900',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    backgroundColor: '#FFF2DC',
  },
  radioDot: {
  width: 12,
  height: 12,
  borderRadius: 6,
  backgroundColor: '#FF9900',
},
  textBlock: {
    flex: 1,
    justifyContent: 'center',
  },
  regionName: {
    fontFamily: 'Inter18Bold',
    fontSize: 14,
    color: '#FF9900',
    marginBottom: 2,
  },
  cityAndAddress: {
    fontFamily: 'Inter18Regular',
    fontSize: 12,
    color: '#A9A9A9',
    marginTop: 0,
  },
  emptyText: {
    textAlign: 'center',
    fontFamily: 'Inter28Bold',
    fontWeight: 'bold',
    color: '#A9A9A9',
    marginTop: 40,
    fontSize: 16,
  },
  touchBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  hidden: {
    width: 0,
    height: 0,
    opacity: 0,
  },
});
